

const ACTIONS = {
  buques: {
    ADD:  "BUQUE_ADD",
    LOAD: 'BUQUE_LOAD',
    COMMIT: 'BUQUE_COMMIT',
    ROLLBACK: 'BUQUE_ROLLBACK',
    ATUALIZE: 'BUQUE_ATUALIZE',
    ATUALIZE_FLOWER: 'BUQUE_ATUALIZE_FLOWER',
    DELETE: 'BUQUE_DELETE',
    LOADONE: 'BUQUE_LOADONE',
    CLEAR: 'BUQUE_CLEAR',
  },

  flowers: {
    LOAD: 'FLOWERS_LOAD',
    COMMIT: 'FLOWERS_COMMIT',
    ROLLBACK: 'FLOWERS_ROLLBACK'
  },

  flower: {
    ADD: 'FLOWER_ADD',
    COMMIT: 'FLOWER_COMMIT',
    ROLLBACK: 'FLOWER_ROLLBACK',
    ATUALIZE: 'FLOWER_ATUALIZE',
    DELETE: 'FLOWER_DELETE',
    LOADONE: 'FLOWER_GET',
  },

  local: {
    ADD: 'LOCAL_ADD',
    COMMIT: 'LOCAL_COMMIT',
    ROLLBACK: 'LOCAL_ROLLBACK',
    REMOVE: 'LOCAL_REMOVE',
    CLEAR: 'LOCAL_CLEAR'
  },
  localedit: {
    ADD: 'LOCALEDIT_ADD',
    COMMIT: 'LOCALEDIT_COMMIT',
    ROLLBACK: 'LOCALEDIT_ROLLBACK',
    REMOVE: 'LOCALEDIT_REMOVE',
    CLEAR: 'LOCALEDIT_CLEAR'
  }
}

export default ACTIONS;